DELETE FROM public.events;
INSERT INTO public.events (title, description, start_datetime, end_datetime, visibility, marketing_request, attachments, created_by, status, unit, event_type) VALUES ('HopeDay', 'Ação realizada totalmente pelo grupo de voluntários, porém as crianças terão espaço no palco para apresentações, programação ainda não definida.', '2025-06-28T08:00:00Z', '2025-06-28T08:00:00Z', 'público', true, '["https://drive.google.com/open?id=1QupJnei--8L6Yrd1PXsdqvd-WBawR-ON"]', 'mkt@anabrasil.org', 'confirmado', 'Evento Geral do Grupo', 'outro');
INSERT INTO public.events (title, description, start_datetime, end_datetime, visibility, marketing_request, attachments, created_by, status, unit, event_type) VALUES ('Festa Encerramento mês férias', 'Uma Festa com doces tipicos de festa junina', '2025-07-31T08:00:00Z', '2025-07-31T08:00:00Z', 'interno', true, '[]', 'mkt@anabrasil.org', 'confirmado', 'Evento Geral do Grupo', 'outro');
INSERT INTO public.events (title, description, start_datetime, end_datetime, visibility, marketing_request, attachments, created_by, status, unit, event_type) VALUES ('Visita Técnica CDMA e Vandercléia, secretaria da Assistencia Social do Municipio ', 'No dia 23 de junho, teremos a visita de nossa secretaria da Assistencia Social, juntamente com sua equipe e acessores. Me indormaram que a mesma tem uma proposta para o território e esta articulando com as OSCs, será a primeira vez, que recebemos a visita da secretaria. ', '2025-06-23T08:00:00Z', '2025-06-23T08:00:00Z', 'interno', true, '[]', 'mkt@anabrasil.org', 'confirmado', 'Evento Geral do Grupo', 'outro');
INSERT INTO public.events (title, description, start_datetime, end_datetime, visibility, marketing_request, attachments, created_by, status, unit, event_type) VALUES ('Teste', 'teste', '2025-06-11T08:00:00Z', '2025-06-11T08:00:00Z', 'público', true, '[]', 'mkt@anabrasil.org', 'confirmado', 'Evento Geral do Grupo', 'outro');
INSERT INTO public.events (title, description, start_datetime, end_datetime, visibility, marketing_request, attachments, created_by, status, unit, event_type) VALUES ('Pluga Automação', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry''s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', '2025-06-13T08:00:00Z', '2025-06-13T08:00:00Z', 'interno', true, '[]', 'mkt@anabrasil.org', 'confirmado', 'Evento Geral do Grupo', 'outro');
INSERT INTO public.events (title, description, start_datetime, end_datetime, visibility, marketing_request, attachments, created_by, status, unit, event_type) VALUES ('Pluga Automação - Agenda "Eventos ANA Brasil"', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry''s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.

', '2025-06-14T08:00:00Z', '2025-06-14T08:00:00Z', 'interno', true, '[]', 'mkt@anabrasil.org', 'confirmado', 'Evento Geral do Grupo', 'outro');
INSERT INTO public.events (title, description, start_datetime, end_datetime, visibility, marketing_request, attachments, created_by, status, unit, event_type) VALUES ('Ação de Saúde', 'Ação promovida pelo Centro de Saúde de nosso território, no ginásio do Cafezinho. Fomos convidados para levar apresentações das crianças.', '2025-07-19T08:00:00Z', '2025-07-19T08:00:00Z', 'público', true, '[]', 'mkt@anabrasil.org', 'confirmado', 'Evento Geral do Grupo', 'outro');
INSERT INTO public.events (title, description, start_datetime, end_datetime, visibility, marketing_request, attachments, created_by, status, unit, event_type) VALUES ('Campeonato de carrinho controle remoto', 'Vamos precisar 5 carrinhos com controle remoto e vamos fazer um circuito no campo para corrida', '2025-07-18T08:00:00Z', '2025-07-18T08:00:00Z', 'interno', true, '["https://drive.google.com/open?id=1ZAe-kFSR99LU2v3_0fkzfc268R_G4bCE"]', 'mkt@anabrasil.org', 'confirmado', 'Evento Geral do Grupo', 'outro');
INSERT INTO public.events (title, description, start_datetime, end_datetime, visibility, marketing_request, attachments, created_by, status, unit, event_type) VALUES ('PicNic ', 'Faremos PicNic com as turmas nos dois períodos, sendo café da manhã às 08:30h e café da tarde, às 14:30h. Nos dias 25, 26 e 30 de junho', '2025-06-25T08:00:00Z', '2025-06-25T08:00:00Z', 'público', true, '[]', 'mkt@anabrasil.org', 'confirmado', 'Evento Geral do Grupo', 'outro');
INSERT INTO public.events (title, description, start_datetime, end_datetime, visibility, marketing_request, attachments, created_by, status, unit, event_type) VALUES ('Aniversariantes do mês e Festa Julina (interna)', 'Neste dia, faremos a comemoração dos aniversariantes do mês com uma mini festa Julina com comidas e brincadeiras típicas da época. O evento acontecerá nos dois períodos (manhã e tarde).', '2025-07-31T08:00:00Z', '2025-07-31T08:00:00Z', 'interno', true, '[]', 'mkt@anabrasil.org', 'confirmado', 'Evento Geral do Grupo', 'outro');
INSERT INTO public.events (title, description, start_datetime, end_datetime, visibility, marketing_request, attachments, created_by, status, unit, event_type) VALUES ('Encontro de Famílias', 'Encontro de Famílias com a presença da Secretária Municipal de Desenvolvimento e Assistência Social, Vandecleya Moro e da diretora do Departamento de Proteção Social Básica do Sistema Único de Assistência Social - DPSB, Ismênia Oki.', '2025-08-23T08:00:00Z', '2025-08-23T08:00:00Z', 'interno', true, '[]', 'mkt@anabrasil.org', 'confirmado', 'Evento Geral do Grupo', 'outro');
INSERT INTO public.events (title, description, start_datetime, end_datetime, visibility, marketing_request, attachments, created_by, status, unit, event_type) VALUES ('ENCONTRO DE FAMÍLIA', 'ENCONTRO DE FAMILIA COM A PRESENÇA DA SECRETÁRIA DA ASSISTENCIA SOCIAL VANDECLEYA ELVIRA DO CARMO SILVA MORO E SUA EQUIPE ', '2025-08-09T08:00:00Z', '2025-08-09T08:00:00Z', 'interno', true, '[]', 'mkt@anabrasil.org', 'confirmado', 'Evento Geral do Grupo', 'outro');
INSERT INTO public.events (title, description, start_datetime, end_datetime, visibility, marketing_request, attachments, created_by, status, unit, event_type) VALUES ('ENCONTRO DE FAMILIAS - CCII ', 'ENCONTRO DE FAMÍLIAS COM CAFÉ DA MANHÃ - CCII ', '2025-08-09T08:00:00Z', '2025-08-09T08:00:00Z', 'interno', true, '[]', 'mkt@anabrasil.org', 'confirmado', 'Evento Geral do Grupo', 'outro');
INSERT INTO public.events (title, description, start_datetime, end_datetime, visibility, marketing_request, attachments, created_by, status, unit, event_type) VALUES ('ENCONTRO DE FAMILIAS - 06 A 14 ', 'APRESENTAÇÕES, EXPOSIÇÃO DE ATIVIDADES E PALESTRTA PARA FAMILIA. ', '2025-08-16T08:00:00Z', '2025-08-16T08:00:00Z', 'interno', true, '[]', 'mkt@anabrasil.org', 'confirmado', 'Evento Geral do Grupo', 'outro');
INSERT INTO public.events (title, description, start_datetime, end_datetime, visibility, marketing_request, attachments, created_by, status, unit, event_type) VALUES ('BAZAR ', 'BAZAR ', '2025-08-30T08:00:00Z', '2025-08-30T08:00:00Z', 'interno', true, '[]', 'mkt@anabrasil.org', 'confirmado', 'Evento Geral do Grupo', 'outro');
INSERT INTO public.events (title, description, start_datetime, end_datetime, visibility, marketing_request, attachments, created_by, status, unit, event_type) VALUES ('PROJETO ABRACE- ESPRO', 'Oficinas Kids', '2025-08-20T08:00:00Z', '2025-08-20T08:00:00Z', 'interno', true, '[]', 'mkt@anabrasil.org', 'confirmado', 'Evento Geral do Grupo', 'outro');
INSERT INTO public.events (title, description, start_datetime, end_datetime, visibility, marketing_request, attachments, created_by, status, unit, event_type) VALUES ('MC LANCHE FELIZ', 'DOADORES COMPRAM MC COM REFRI LEVA NAS UNIDADES', '2025-08-22T08:00:00Z', '2025-08-22T08:00:00Z', 'interno', true, '[]', 'mkt@anabrasil.org', 'confirmado', 'Evento Geral do Grupo', 'outro');
INSERT INTO public.events (title, description, start_datetime, end_datetime, visibility, marketing_request, attachments, created_by, status, unit, event_type) VALUES ('Mc dia feliz ', 'No dia 22 de agosto, nossos usuarios serão contemplados com lanches do McDonald''s, durante os 3 periodos de atendimentos, seguimos no 3º ano desta ação, que vem benifiando nossos usuarios. A iniciativa parte de grupos de amigos e empresarios. ', '2025-08-22T08:00:00Z', '2025-08-22T08:00:00Z', 'interno', true, '[]', 'mkt@anabrasil.org', 'confirmado', 'Evento Geral do Grupo', 'outro');
INSERT INTO public.events (title, description, start_datetime, end_datetime, visibility, marketing_request, attachments, created_by, status, unit, event_type) VALUES ('Capacitação Brasiliense ', 'Nossos Trilhandos irão participar de mais uma capacitação direcionada ao mundo do trabalho, em empresa Brasiliense. Os mesmos irão receber um café da manhã e farão um tour pela empresa. ', '2025-08-25T08:00:00Z', '2025-08-25T08:00:00Z', 'público', true, '[]', 'mkt@anabrasil.org', 'confirmado', 'Evento Geral do Grupo', 'outro');
INSERT INTO public.events (title, description, start_datetime, end_datetime, visibility, marketing_request, attachments, created_by, status, unit, event_type) VALUES ('Palestra com mulheres - MM ', 'Palestra direcionada parea mulheres, com o tema Menopausa. ', '2025-08-30T08:00:00Z', '2025-08-30T08:00:00Z', 'público', true, '[]', 'mkt@anabrasil.org', 'confirmado', 'Evento Geral do Grupo', 'outro');
INSERT INTO public.events (title, description, start_datetime, end_datetime, visibility, marketing_request, attachments, created_by, status, unit, event_type) VALUES ('Palestra Trilhando Futuro - Luxótica ', 'Palestra Luxótica ', '2025-08-27T08:00:00Z', '2025-08-27T08:00:00Z', 'público', true, '[]', 'mkt@anabrasil.org', 'confirmado', 'Evento Geral do Grupo', 'outro');
INSERT INTO public.events (title, description, start_datetime, end_datetime, visibility, marketing_request, attachments, created_by, status, unit, event_type) VALUES ('Entre Laços e Abraços ', 'Encontro com roda de conversa e café, abordaremos o tema Violência contra a mulher. ', '2025-08-22T08:00:00Z', '2025-08-22T08:00:00Z', 'interno', true, '[]', 'mkt@anabrasil.org', 'confirmado', 'Evento Geral do Grupo', 'outro');
INSERT INTO public.events (title, description, start_datetime, end_datetime, visibility, marketing_request, attachments, created_by, status, unit, event_type) VALUES ('Visita de deputado - PL ', 'Visita em unidade Dic, de deputado Lucas - PL a fim de conhecer o serviço e entender a dinâmica desenvilvida. ', '2025-09-04T08:00:00Z', '2025-09-04T08:00:00Z', 'interno', true, '[]', 'mkt@anabrasil.org', 'confirmado', 'Evento Geral do Grupo', 'outro');
INSERT INTO public.events (title, description, start_datetime, end_datetime, visibility, marketing_request, attachments, created_by, status, unit, event_type) VALUES ('DESFILE CIVICO ', 'NOSSA UNIDADE PARTICIPARÁ DO DESFILE DE SETE DE SETEMBRO.', '2025-09-07T08:00:00Z', '2025-09-07T08:00:00Z', 'interno', true, '[]', 'mkt@anabrasil.org', 'confirmado', 'Evento Geral do Grupo', 'outro');
INSERT INTO public.events (title, description, start_datetime, end_datetime, visibility, marketing_request, attachments, created_by, status, unit, event_type) VALUES ('REUNIÃO DE FAMÍLIAS - COM A EQUIPE CDMA E SECRETARIA DA ASSISTENCIA SOCIAL VANDERCLÉIA ', 'Palestra com a comunidade ', '2025-09-13T08:00:00Z', '2025-09-13T08:00:00Z', 'público', true, '[]', 'mkt@anabrasil.org', 'confirmado', 'Evento Geral do Grupo', 'outro');
INSERT INTO public.events (title, description, start_datetime, end_datetime, visibility, marketing_request, attachments, created_by, status, unit, event_type) VALUES ('Capacitação Brasiliense ', 'Nosso grupo do Trilhando Futuro, participará de mais uma palestra em empresa Brasiliense, sobre Mundo Corporativo ', '2025-09-25T08:00:00Z', '2025-09-25T08:00:00Z', 'público', true, '[]', 'mkt@anabrasil.org', 'confirmado', 'Evento Geral do Grupo', 'outro');
INSERT INTO public.events (title, description, start_datetime, end_datetime, visibility, marketing_request, attachments, created_by, status, unit, event_type) VALUES ('Culto Evangelistico ', 'Culto evangelistico com presença de escritor com necessidades especiais ', '2025-09-12T14:00:00:00Z', '2025-09-12T14:00:00:00Z', 'interno', true, '[]', 'mkt@anabrasil.org', 'confirmado', 'Evento Geral do Grupo', 'outro');
INSERT INTO public.events (title, description, start_datetime, end_datetime, visibility, marketing_request, attachments, created_by, status, unit, event_type) VALUES ('HopeDay', 'Conforme alinhamento com a gestão, os grupos musicais das 02 unidades (Nilópolis e DIC) participarão do HopeDay, logo após o ensaio. Horário aproximado do evento das 11h às 15h', '2025-10-11T11:00:00:00Z', '2025-10-11T11:00:00:00Z', 'público', true, '["https://drive.google.com/open?id=132tFYmMKTwoqTbOZf41CWB1_1-_3YZa6"]', 'mkt@anabrasil.org', 'confirmado', 'Evento Geral do Grupo', 'outro');
INSERT INTO public.events (title, description, start_datetime, end_datetime, visibility, marketing_request, attachments, created_by, status, unit, event_type) VALUES ('Palestra MM - Saúde Bucal ', 'Palestra MM sobre higiêne bucal, com as mães, adolesecentes, adultas ', '2025-10-25T14:00:00:00Z', '2025-10-25T14:00:00:00Z', 'público', true, '["https://drive.google.com/open?id=19dAFiwa7ymVNkLd5nQlvtCibLM2GxuRP"]', 'mkt@anabrasil.org', 'confirmado', 'Evento Geral do Grupo', 'outro');
INSERT INTO public.events (title, description, start_datetime, end_datetime, visibility, marketing_request, attachments, created_by, status, unit, event_type) VALUES ('Ação voluntários UNIMETROCAMP', 'Alunos trarão infláveis e farão pintura facial.', '2025-10-24T09:00:00:00Z', '2025-10-24T09:00:00:00Z', 'público', true, '[]', 'mkt@anabrasil.org', 'confirmado', 'Evento Geral do Grupo', 'outro');
INSERT INTO public.events (title, description, start_datetime, end_datetime, visibility, marketing_request, attachments, created_by, status, unit, event_type) VALUES ('Palestra Finanças ', 'A palestra tem com objetivo orientar os adolescentes sobre a importância da educação financeira e da boa administração do primeiro salário, bem como planejar gastos, consumo consciente, diferença entre necessidade e desejo, importância de poupar e ter metas financeiras para o futuro', '2025-10-28T14:00:00:00Z', '2025-10-28T14:00:00:00Z', 'público', true, '[]', 'mkt@anabrasil.org', 'confirmado', 'Evento Geral do Grupo', 'outro');
INSERT INTO public.events (title, description, start_datetime, end_datetime, visibility, marketing_request, attachments, created_by, status, unit, event_type) VALUES ('Palestra Sobre Autocuidado', 'A proposta tem com objetivo conscientizar sobre a importância do autocuidado  como parte da saúde fisica, mental, emocional e espiritual.', '2025-10-30T09:30:00:00Z', '2025-10-30T09:30:00:00Z', 'público', true, '[]', 'mkt@anabrasil.org', 'confirmado', 'Evento Geral do Grupo', 'outro');
INSERT INTO public.events (title, description, start_datetime, end_datetime, visibility, marketing_request, attachments, created_by, status, unit, event_type) VALUES ('Papel da educação na transformação pessoal e social', 'O projeto tem como objetivo promover reflexões sobre o papel da educação na transformação pessoal e social, incentivando os participantes a reconhecerem seu potencial de crescimento por meio do aprendizado.', '2025-10-29T09:00:00:00Z', '2025-10-29T09:00:00:00Z', 'público', true, '[]', 'mkt@anabrasil.org', 'confirmado', 'Evento Geral do Grupo', 'outro');
INSERT INTO public.events (title, description, start_datetime, end_datetime, visibility, marketing_request, attachments, created_by, status, unit, event_type) VALUES ('Encontro de Famílias', 'Receberemos as famílias com um café da manhã, na sequencia teremos apresentações da crianças e uma palavra final.', '2025-11-08T09:00:00:00Z', '2025-11-08T09:00:00:00Z', 'interno', true, '[]', 'mkt@anabrasil.org', 'confirmado', 'Evento Geral do Grupo', 'outro');
INSERT INTO public.events (title, description, start_datetime, end_datetime, visibility, marketing_request, attachments, created_by, status, unit, event_type) VALUES (' ESPRO', 'Projeto do Gestores do Futuro planejou um dia de brincadeiras para as crianças. Laços da Esperança tem como missão promover acolhimento, educação e alegria para crianças vulneráveis, oferecendo oportunidades de desenvolvimento integral e construindo vínculos transformadores com dignidade e afeto', '2025-11-12T08:00:00:00Z', '2025-11-12T08:00:00:00Z', 'interno', true, '[]', 'mkt@anabrasil.org', 'confirmado', 'Evento Geral do Grupo', 'outro');
INSERT INTO public.events (title, description, start_datetime, end_datetime, visibility, marketing_request, attachments, created_by, status, unit, event_type) VALUES ('Sorriso é Coisa Séria', 'Na atividade proposta, crianças da instituição ANA - Santana, de 06 a 10 anos, participarão de atividades lúdico educativas de saúde bucal realizadas pela equipe de dentistas do Sesc Campinas, com orientações sobre cuidados e higiene e distribuição de kits de saúde bucal. A ação será complementada pela intervenção "O Mundo em Minha Boca", na qual o grupo propõe um resgate poético e musical sobre as funções da boca como meio de experimentação do mundo e forma de expressão. O espetáculo é interativo e integrado com uma oficina de origami.', '2025-11-06T08:30:00:00Z', '2025-11-06T08:30:00:00Z', 'interno', true, '[]', 'mkt@anabrasil.org', 'confirmado', 'Evento Geral do Grupo', 'outro');
INSERT INTO public.events (title, description, start_datetime, end_datetime, visibility, marketing_request, attachments, created_by, status, unit, event_type) VALUES ('Festa da Primaveira', 'O Evento tem o intuito de promover a integração e fortalecer os vinculos entro os participantes e a comunidade local', '2025-11-22T14:00:00:00Z', '2025-11-22T14:00:00:00Z', 'público', true, '[]', 'mkt@anabrasil.org', 'confirmado', 'Evento Geral do Grupo', 'outro');
INSERT INTO public.events (title, description, start_datetime, end_datetime, visibility, marketing_request, attachments, created_by, status, unit, event_type) VALUES ('TROCA DE FAIXA KARATÊ', 'Atividade de Karatê vai trocar a faixa  ', '2025-12-05T14:00:00:00Z', '2025-12-05T14:00:00:00Z', 'interno', true, '[]', 'mkt@anabrasil.org', 'confirmado', 'Evento Geral do Grupo', 'outro');
INSERT INTO public.events (title, description, start_datetime, end_datetime, visibility, marketing_request, attachments, created_by, status, unit, event_type) VALUES ('Recital ', 'Apresentação da Flauta com parceria com igreja Presbiteriana', '2025-11-30T09:00:00:00Z', '2025-11-30T09:00:00:00Z', 'público', true, '["https://drive.google.com/open?id=1LBOAFYPgCao9qMzCni2Ck7X59-KwU-at"]', 'mkt@anabrasil.org', 'confirmado', 'Evento Geral do Grupo', 'outro');
INSERT INTO public.events (title, description, start_datetime, end_datetime, visibility, marketing_request, attachments, created_by, status, unit, event_type) VALUES ('Palestra Saúde Emocional', 'Palestra Saúde Emocional, com pastor e psicologo Fred Dias', '2025-11-28T09:00:00:00Z', '2025-11-28T09:00:00:00Z', 'interno', true, '[]', 'mkt@anabrasil.org', 'confirmado', 'Evento Geral do Grupo', 'outro');
INSERT INTO public.events (title, description, start_datetime, end_datetime, visibility, marketing_request, attachments, created_by, status, unit, event_type) VALUES ('Parada de Natal', 'A Parada de Natal deste ano acontecerá na Avenida Francisco Glicério e  será um momento especial de celebração, integração e alegria para toda a comunidade. O evento contará com apresentações temáticas, música, personagens natalinos, carros decorados e diversas intervenções artísticas que vão transformar a avenida em um verdadeiro cenário mágico de fim de ano.', '2025-12-06T19:00:00:00Z', '2025-12-06T19:00:00:00Z', 'público', true, '[]', 'mkt@anabrasil.org', 'confirmado', 'Evento Geral do Grupo', 'outro');
INSERT INTO public.events (title, description, start_datetime, end_datetime, visibility, marketing_request, attachments, created_by, status, unit, event_type) VALUES ('Coral Ana Dic - Igreja do Nazareno Jardim Aeronave', 'Nosso coral fará uma apresentação especial de Natal ', '2025-12-07T18:00:00:00Z', '2025-12-07T18:00:00:00Z', 'público', true, '[]', 'mkt@anabrasil.org', 'confirmado', 'Evento Geral do Grupo', 'outro');
INSERT INTO public.events (title, description, start_datetime, end_datetime, visibility, marketing_request, attachments, created_by, status, unit, event_type) VALUES ('Natal Feliz - Manaim', 'O Natal Feliz do Manaim será  um dia de celebração, solidariedade e integração entre as três unidades do Social, que se uniram para proporcionar uma experiência inesquecível aos nossos usuários. Este ano, contamos com o apoio fundamental do Hopy Day,  Alcance e da JNI.', '2025-12-13T07:00:00:00Z', '2025-12-13T07:00:00:00Z', 'público', true, '[]', 'mkt@anabrasil.org', 'confirmado', 'Evento Geral do Grupo', 'outro');
INSERT INTO public.events (title, description, start_datetime, end_datetime, visibility, marketing_request, attachments, created_by, status, unit, event_type) VALUES ('Espetaculo Principe do Egito', 'O Serviço de Convivência e Fortalecimento de Vínculos está preparando uma apresentação especial baseada na história do “Príncipe do Egito”, desenvolvida integralmente pelos nossos usuários, com acompanhamento da equipe técnica e educadores. O espetáculo busca promover protagonismo, criatividade e fortalecimento de vínculos comunitários por meio da arte, música e expressão corporal.', '2025-12-19T19:00:00:00Z', '2025-12-19T19:00:00:00Z', 'público', true, '[]', 'mkt@anabrasil.org', 'confirmado', 'Evento Geral do Grupo', 'outro');
INSERT INTO public.events (title, description, start_datetime, end_datetime, visibility, marketing_request, attachments, created_by, status, unit, event_type) VALUES ('Cantata de Natal  ( Natal Brasileiro)', 'Cantata de Natal Igreja Jardim Aeronave com Participação CCII', '2025-12-21T09:00:00:00Z', '2025-12-21T09:00:00:00Z', 'público', true, '[]', 'mkt@anabrasil.org', 'confirmado', 'Evento Geral do Grupo', 'outro');
INSERT INTO public.events (title, description, start_datetime, end_datetime, visibility, marketing_request, attachments, created_by, status, unit, event_type) VALUES ('CAFÉ DA MANHÃ COM FAMILIAS ', 'NO DIA 21/02/2026 TEREMOS NOSSO CAFÉ COM FAMILIAS, ONDE TEREMOS A PRESENÇA DA SECRETARIA DA ASSISTENCIA SOCIAL - VANDERCLÉIA MORO. SERÁ UM ENCONTRO INFORMATIVO, ONDE AS FAMILIAS RECEBERÃO INFORMAÇÕES SOBRE NOSSO SERVIÇO, E TAMBÉM SOBRE SERVIÇOS, QUE HOJE ESTÃO DISPONIVEIS PARA A COMUNIDADE. SERÁ DIVULGADO NESTE DIA, O PRIMEIRO VARAL SOLIDARIO DO ANA DIC, EM PARCERIA COM A SECRETARIA DA ASSISTENCIA. ', '2026-02-21T09:00:00:00Z', '2026-02-21T09:00:00:00Z', 'público', true, '[]', 'mkt@anabrasil.org', 'confirmado', 'Evento Geral do Grupo', 'outro');
INSERT INTO public.events (title, description, start_datetime, end_datetime, visibility, marketing_request, attachments, created_by, status, unit, event_type) VALUES ('VARAL SOLIDÁRIO', 'O Varal Solidário, na Unidade Nilópolis, em parceria com o Programa Próximo Passo. Será uma manhã especial de cuidado, orientação e apoio às famílias da comunidade.', '2026-02-28T09:00:00:00Z', '2026-02-28T09:00:00:00Z', 'interno', true, '["https://drive.google.com/open?id=1-m9VnH0TX2icrsTFf-iG6nLUt7BFVgXq"]', 'mkt@anabrasil.org', 'confirmado', 'Evento Geral do Grupo', 'outro');
INSERT INTO public.events (title, description, start_datetime, end_datetime, visibility, marketing_request, attachments, created_by, status, unit, event_type) VALUES ('ENCONTRO DE FAMILIA', 'Um momento para apresentar nossas atividades , explicar nosso serviço de apoio com  Serviço Social e Psicologia, e  se encantar com o talento das crianças nas apresentações.', '2026-03-07T09:00:00:00Z', '2026-03-07T09:00:00:00Z', 'interno', true, '[]', 'mkt@anabrasil.org', 'confirmado', 'Evento Geral do Grupo', 'outro');
INSERT INTO public.events (title, description, start_datetime, end_datetime, visibility, marketing_request, attachments, created_by, status, unit, event_type) VALUES ('Encontro de Famílias', 'Os Encontros de Família são fundamentais para o nosso trabalho e tem como principal objetivo promover o fortalecimento de vínculos entres as crianças e adolescentes e seus familiares. Isso ocorre a partir de apresentações das atividades que realizaram ao longo do bimestre, bem como a partir de atividades interativas com as família e palestras cuja temática é escolhida de acordo com a necessidade identificada no dia a dia do acompanhamento com as famílias.', '2026-03-21T08:00:00:00Z', '2026-03-21T08:00:00:00Z', 'interno', true, '[]', 'mkt@anabrasil.org', 'confirmado', 'Evento Geral do Grupo', 'outro');
INSERT INTO public.events (title, description, start_datetime, end_datetime, visibility, marketing_request, attachments, created_by, status, unit, event_type) VALUES ('VARAL SOLIDÁRIO ', 'Evento realizado pela Prefeitura de Camppinas - Secretaria da Assistencia Social, durante o evento teremos - doações de roupas, atualização do cadastro unico, orientações auxilios sociais, vagas de empregos, cursos / captações, orientação MEI, exame de vista, corte de cabelo, aula de pilates. ', '2026-03-21T08:00:00:00Z', '2026-03-21T08:00:00:00Z', 'público', true, '[]', 'mkt@anabrasil.org', 'confirmado', 'Evento Geral do Grupo', 'outro');
INSERT INTO public.events (title, description, start_datetime, end_datetime, visibility, marketing_request, attachments, created_by, status, unit, event_type) VALUES ('Teatro de Páscoa', 'O teatro é comemorativo, por ocasião da Páscoa, a peça será apresentada pelo Grupo Ecco, um grupo voluntário cristão. O evento ocorrerá de manhã e a tarde no mesmo dia, na quadra da unidade Nilópolis, com participação das crianças da unidade Santana.', '2026-03-30T08:00:00:00Z', '2026-03-30T08:00:00:00Z', 'interno', true, '["https://drive.google.com/open?id=1SxEwT2RqMW6QTdqBMJL0Ctj59sQzptD2"]', 'mkt@anabrasil.org', 'confirmado', 'Evento Geral do Grupo', 'outro');
INSERT INTO public.events (title, description, start_datetime, end_datetime, visibility, marketing_request, attachments, created_by, status, unit, event_type) VALUES ('Café da manhã especial ', 'ema: Características do Desenvolvimento Infantil dos 06 aos 9 anos 
Participe desse momento de aprendizado, compartilhamento, escuta e orientações.
Entrega de alimentos para os responsáveis presentes!', '2026-03-26T09:00:00:00Z', '2026-03-26T09:00:00:00Z', 'interno', true, '[]', 'mkt@anabrasil.org', 'confirmado', 'Evento Geral do Grupo', 'outro');
INSERT INTO public.events (title, description, start_datetime, end_datetime, visibility, marketing_request, attachments, created_by, status, unit, event_type) VALUES ('Teatro de Páscoa', 'A verdadeira Páscoa ', '2026-03-30T09:00:00:00Z', '2026-03-30T09:00:00:00Z', 'interno', true, '[]', 'mkt@anabrasil.org', 'confirmado', 'Evento Geral do Grupo', 'outro');
INSERT INTO public.events (title, description, start_datetime, end_datetime, visibility, marketing_request, attachments, created_by, status, unit, event_type) VALUES ('Teatro de Páscoa', 'A verdadeira Páscoa! ', '2026-03-30T09:00:00:00Z', '2026-03-30T09:00:00:00Z', 'interno', true, '[]', 'mkt@anabrasil.org', 'confirmado', 'Evento Geral do Grupo', 'outro');
INSERT INTO public.events (title, description, start_datetime, end_datetime, visibility, marketing_request, attachments, created_by, status, unit, event_type) VALUES ('HOPE DAY ', 'Apresentação ANA Nilópolis e DIC', '2026-03-28T09:00:00:00Z', '2026-03-28T09:00:00:00Z', 'público', true, '[]', 'mkt@anabrasil.org', 'confirmado', 'Evento Geral do Grupo', 'outro');
INSERT INTO public.events (title, description, start_datetime, end_datetime, visibility, marketing_request, attachments, created_by, status, unit, event_type) VALUES ('Ação Otica Prime', 'A ação conta com a parceria da Ótica Prime, que está contribuindo com a promoção da saúde visual dos nossos atendidos, além da doação de óculos', '2026-03-30T08:00:00:00Z', '2026-03-30T08:00:00:00Z', 'interno', true, '[]', 'mkt@anabrasil.org', 'confirmado', 'Evento Geral do Grupo', 'outro');
INSERT INTO public.events (title, description, start_datetime, end_datetime, visibility, marketing_request, attachments, created_by, status, unit, event_type) VALUES ('Roda de Conversa (Saúde Emocional)', 'A roda de conversa sobre saúde emocional, sera realizada com os idosos e conduzida por psicopedagoga voluntária, proporcionando um momento de acolhimento, escuta e troca de experiências. A atividade vai contribuir para o fortalecimento de vínculos, promoção do bem-estar e prevenção do isolamento social, alinhando-se aos objetivos do SCFV.', '2023-03-31T11:00:00:00Z', '2023-03-31T11:00:00:00Z', 'interno', true, '[]', 'mkt@anabrasil.org', 'confirmado', 'Evento Geral do Grupo', 'outro');
INSERT INTO public.events (title, description, start_datetime, end_datetime, visibility, marketing_request, attachments, created_by, status, unit, event_type) VALUES ('Visita Empresa Brasiliense', 'A visita à empresa Brasiliense, que será realizada com os adolescentes do projeto Trilhando Futuro, tem como objetivo proporcionar conhecimento sobre o ambiente profissional e aproximá-los do mundo do trabalho. Durante a atividade, os participantes irão conhecer a empresa e participar de palestras orientativas, contribuindo para o desenvolvimento de habilidades, ampliação de perspectivas e preparação para futuras oportunidades profissionais.', '2026-03-30T09:00:00:00Z', '2026-03-30T09:00:00:00Z', 'público', true, '[]', 'mkt@anabrasil.org', 'confirmado', 'Evento Geral do Grupo', 'outro');
INSERT INTO public.events (title, description, start_datetime, end_datetime, visibility, marketing_request, attachments, created_by, status, unit, event_type) VALUES ('Ação Social - Objetivo ', 'O colégio Objetivo irá realizar uma ação social, em unidade Dic, por comemoração a Pascoa, onde estará entregando 1 caixa de bombom para cada atendido. Durante o periodo estaremos com atividades socieducativas e recreação. ', '2026-04-02T13:30:00:00Z', '2026-04-02T13:30:00:00Z', 'público', true, '[]', 'mkt@anabrasil.org', 'confirmado', 'Evento Geral do Grupo', 'outro');
INSERT INTO public.events (title, description, start_datetime, end_datetime, visibility, marketing_request, attachments, created_by, status, unit, event_type) VALUES ('Páscoa - JNI', 'Local e Público-Alvo: O evento foca nas crianças das comunidades do bairro Gênesis e do ANA Nilópolis (unidade da Associação Nazarena Assistencial no Jardim Nilópolis). A celebração ocorre no Ginásio Municipal Dep. Nabi Abi Chedid, localizado no Parque Anhumas (Rua Ipê da Várzea).
Atividades e Atrações:
Apresentações Culturais: O evento conta com apresentações  ANA Nilópolis do Batuque e Hip Hop.
Diversão e Alimentação: Estão previstas atividades de recreação, brinquedos infláveis, além da distribuição de comidas para as crianças participantes.
Propósito: Além do lazer, a JNI busca transmitir o "verdadeiro significado da Páscoa" através de momentos de louvor e comunhão. ', '2026-04-04T09:00:00:00Z', '2026-04-04T09:00:00:00Z', 'público', true, '[]', 'mkt@anabrasil.org', 'confirmado', 'Evento Geral do Grupo', 'outro');
INSERT INTO public.events (title, description, start_datetime, end_datetime, visibility, marketing_request, attachments, created_by, status, unit, event_type) VALUES ('Exposição Carbono Zero', 'O Projeto Futuro Carbono Zero percorre o estado levando arte, tecnologia e reflexões sobre o planeta em uma carreta transformada em alegria. A amostra cria um percurso sensorial que une criatividade e educação ambiental.

', '2026-03-31T14:00:00:00Z', '2026-03-31T14:00:00:00Z', 'público', true, '[]', 'mkt@anabrasil.org', 'confirmado', 'Evento Geral do Grupo', 'outro');
INSERT INTO public.events (title, description, start_datetime, end_datetime, visibility, marketing_request, attachments, created_by, status, unit, event_type) VALUES ('Culto de Páscoa e almoço especial ', 'No dia 02/04/2026, teremos nosso culto de Páscoa, com a contadora de histórias - Tia Polly ', '2026-04-02T14:00:00:00Z', '2026-04-02T14:00:00:00Z', 'interno', false, '[]', 'mkt@anabrasil.org', 'confirmado', 'Evento Geral do Grupo', 'outro');
INSERT INTO public.events (title, description, start_datetime, end_datetime, visibility, marketing_request, attachments, created_by, status, unit, event_type) VALUES ('Palestra Com Grupo MM - Primeiros Socorros', 'Uma palestra sobre primeiros socorros ensina como agir em emergências até a chegada de ajuda profissional.', '2026-04-25T14:00:00:00Z', '2026-04-25T14:00:00:00Z', 'interno', true, '[]', 'mkt@anabrasil.org', 'confirmado', 'Evento Geral do Grupo', 'outro');
INSERT INTO public.events (title, description, start_datetime, end_datetime, visibility, marketing_request, attachments, created_by, status, unit, event_type) VALUES ('Integração funcionários- Social', 'Integração de funcionários das unidades do Social para alinhamento de processos.', '2026-04-17T07:45:00:00Z', '2026-04-17T07:45:00:00Z', 'interno', true, '[]', 'mkt@anabrasil.org', 'confirmado', 'Evento Geral do Grupo', 'outro');
INSERT INTO public.events (title, description, start_datetime, end_datetime, visibility, marketing_request, attachments, created_by, status, unit, event_type) VALUES ('Encontro de Profissões', 'O Encontro de Profissões Objetivo é um evento gratuito que conecta estudantes do ensino médio com profissionais renomados de diversas áreas. Uma manhã dedicada a esclarecer dúvidas, apresentar possibilidades e inspirar o seu futuro profissional.', '2026-05-09T08:30:00:00Z', '2026-05-09T08:30:00:00Z', 'público', true, '[]', 'mkt@anabrasil.org', 'confirmado', 'Evento Geral do Grupo', 'outro');
INSERT INTO public.events (title, description, start_datetime, end_datetime, visibility, marketing_request, attachments, created_by, status, unit, event_type) VALUES ('Encontro de mulheres - Mulheres que florescem ', 'Maio é trabalhado a semana da familia, normalmente não comemoramos o "Dia das mães" e sim semana da familia. Mas esse ano, gostariamos de reunir mulheres que cuidam. Assim oferecermos um tempo de qualidade, com uma proposta dinamica e acolhedora. O encontro “Mulheres que Florescem” surge como uma proposta de acolhimento, fortalecimento e renovação. Assim como uma flor precisa de tempo, cuidado e condições adequadas para florescer, cada mulher também passa por processos necessários para alcançar seu potencial. Este evento busca proporcionar um ambiente seguro onde mulheres possam se reconectar consigo mesmas, fortalecer sua identidade e compreender que mesmo em meio às dificuldades, é possível florescer.
', '2026-05-30T14:00:00:00Z', '2026-05-30T14:00:00:00Z', 'interno', true, '[]', 'mkt@anabrasil.org', 'confirmado', 'Evento Geral do Grupo', 'outro');
INSERT INTO public.events (title, description, start_datetime, end_datetime, visibility, marketing_request, attachments, created_by, status, unit, event_type) VALUES ('Baile da Pessoa Idosa', 'O Baile da Pessoa Idosa, realizado pelo CMI, tem como proposta promover a integração, socialização e valorização das pessoas idosas, proporcionando um momento de lazer, convivência e fortalecimento de vínculos.', '2026-04-30T14:00:00:00Z', '2026-04-30T14:00:00:00Z', 'público', true, '[]', 'mkt@anabrasil.org', 'confirmado', 'Evento Geral do Grupo', 'outro');
INSERT INTO public.events (title, description, start_datetime, end_datetime, visibility, marketing_request, attachments, created_by, status, unit, event_type) VALUES ('Entrega dos óculos com Parceiro Otica Prime', 'Será feita a entrega dos óculos pela empresa parceira ótica prime', '2026-04-29T08:00:00:00Z', '2026-04-29T08:00:00:00Z', 'interno', true, '[]', 'mkt@anabrasil.org', 'confirmado', 'Evento Geral do Grupo', 'outro');
INSERT INTO public.events (title, description, start_datetime, end_datetime, visibility, marketing_request, attachments, created_by, status, unit, event_type) VALUES ('Abertura do Congemas ', '26° Encontro Congemas- Sudeste 
( gestores,conselheiros e trabalhadores  do território).', '2026-05-07T10:00:00:00Z', '2026-05-07T10:00:00:00Z', 'público', true, '[]', 'mkt@anabrasil.org', 'confirmado', 'Evento Geral do Grupo', 'outro');
INSERT INTO public.events (title, description, start_datetime, end_datetime, visibility, marketing_request, attachments, created_by, status, unit, event_type) VALUES ('Passeata 18 de Maio ', 'Atividade direcionada para o território Sudoeste, onde OSCs estarã juntas, compartilhando informações relevantes sobre o tema 18 de Maio. A atividade é realizada em conjunto e orgqanizada em nossas reuniões mensais do Agita Rede. ', '2026-05-15T08:00:00:00Z', '2026-05-15T08:00:00:00Z', 'público', true, '[]', 'mkt@anabrasil.org', 'confirmado', 'Evento Geral do Grupo', 'outro');
INSERT INTO public.events (title, description, start_datetime, end_datetime, visibility, marketing_request, attachments, created_by, status, unit, event_type) VALUES ('Festa da Amizade ', 'Apresentação de Coral e Dança em Festa da Amizade - unidade Nave Mãe Anisio ', '2026-05-28T09:00:00:00Z', '2026-05-28T09:00:00:00Z', 'interno', true, '[]', 'mkt@anabrasil.org', 'confirmado', 'Evento Geral do Grupo', 'outro');
INSERT INTO public.events (title, description, start_datetime, end_datetime, visibility, marketing_request, attachments, created_by, status, unit, event_type) VALUES ('Bazar Ana Dic ', 'Bazar em unidade Dic, com roupas com valor de R$ 1,00, a fim de beneficiar as familias e comunidade. ', '2026-05-25T09:00:00:00Z', '2026-05-25T09:00:00:00Z', 'interno', true, '[]', 'mkt@anabrasil.org', 'confirmado', 'Evento Geral do Grupo', 'outro');
INSERT INTO public.events (title, description, start_datetime, end_datetime, visibility, marketing_request, attachments, created_by, status, unit, event_type) VALUES ('Ação 18  Maio', 'O 18 de Maio é o Dia Nacional de Combate ao Abuso e à Exploração Sexual de Crianças e Adolescentes no Brasil, marco da campanha #FaçaBonito. A data visa mobilizar a sociedade para proteger menores, denunciar abusos e quebrar o ciclo de violência, com o Disque 100 como principal ferramenta de denúncia', '2026-05-23T08:00:00:00Z', '2026-05-23T08:00:00:00Z', 'público', true, '[]', 'mkt@anabrasil.org', 'confirmado', 'Evento Geral do Grupo', 'outro');