-- Executando atualizações de unidades em massa baseadas na lógica de e-mail da planilha
UPDATE public.events SET unit = 'Evento Geral do Grupo' WHERE title = 'HopeDay' AND start_datetime::date = '2025-06-28';
UPDATE public.events SET unit = 'Evento Geral do Grupo' WHERE title = 'Festa Encerramento mês férias' AND start_datetime::date = '2025-07-31';
UPDATE public.events SET unit = 'Evento Geral do Grupo' WHERE title = 'Visita Técnica CDMA e Vandercléia, secretaria da Assistencia Social do Municipio' AND start_datetime::date = '2025-06-23';
UPDATE public.events SET unit = 'Nilópolis' WHERE title = 'Ação de Saúde' AND start_datetime::date = '2025-07-19';
UPDATE public.events SET unit = 'Santana' WHERE title = 'Campeonato de carrinho controle remoto' AND start_datetime::date = '2025-07-18';
UPDATE public.events SET unit = 'Nilópolis' WHERE title = 'PicNic' AND start_datetime::date = '2025-06-25';
UPDATE public.events SET unit = 'Santana' WHERE title = 'Aniversariantes do mês e Festa Julina (interna)' AND start_datetime::date = '2025-07-31';
UPDATE public.events SET unit = 'Nilópolis' WHERE title = 'Encontro de Famílias' AND start_datetime::date = '2025-08-23';
UPDATE public.events SET unit = 'Santana' WHERE title = 'ENCONTRO DE FAMÍLIA' AND start_datetime::date = '2025-08-09';
UPDATE public.events SET unit = 'DIC' WHERE title = 'ENCONTRO DE FAMILIAS - CCII' AND start_datetime::date = '2025-08-09';
UPDATE public.events SET unit = 'DIC' WHERE title = 'ENCONTRO DE FAMILIAS - 06 A 14' AND start_datetime::date = '2025-08-16';
UPDATE public.events SET unit = 'DIC' WHERE title = 'BAZAR' AND start_datetime::date = '2025-08-30';
UPDATE public.events SET unit = 'Santana' WHERE title = 'PROJETO ABRACE- ESPRO' AND start_datetime::date = '2025-08-20';
UPDATE public.events SET unit = 'Santana' WHERE title = 'MC LANCHE FELIZ' AND start_datetime::date = '2025-08-22';
UPDATE public.events SET unit = 'DIC' WHERE title = 'Mc dia feliz' AND start_datetime::date = '2025-08-22';
UPDATE public.events SET unit = 'DIC' WHERE title = 'Capacitação Brasiliense' AND start_datetime::date = '2025-08-25';
UPDATE public.events SET unit = 'DIC' WHERE title = 'Palestra com mulheres - MM' AND start_datetime::date = '2025-08-30';
UPDATE public.events SET unit = 'DIC' WHERE title = 'Palestra Trilhando Futuro - Luxótica' AND start_datetime::date = '2025-08-27';
UPDATE public.events SET unit = 'DIC' WHERE title = 'Entre Laços e Abraços' AND start_datetime::date = '2025-08-22';
UPDATE public.events SET unit = 'DIC' WHERE title = 'Visita de deputado - PL' AND start_datetime::date = '2025-09-04';
UPDATE public.events SET unit = 'DIC' WHERE title = 'DESFILE CIVICO' AND start_datetime::date = '2025-09-07';
UPDATE public.events SET unit = 'DIC' WHERE title = 'REUNIÃO DE FAMÍLIAS - COM A EQUIPE CDMA E SECRETARIA DA ASSISTENCIA SOCIAL VANDERCLÉIA' AND start_datetime::date = '2025-09-13';
UPDATE public.events SET unit = 'DIC' WHERE title = 'Capacitação Brasiliense' AND start_datetime::date = '2025-09-25';
UPDATE public.events SET unit = 'DIC' WHERE title = 'Culto Evangelistico' AND start_datetime::date = '2025-09-12';
UPDATE public.events SET unit = 'Nilópolis' WHERE title = 'HopeDay' AND start_datetime::date = '2025-10-11';
UPDATE public.events SET unit = 'DIC' WHERE title = 'Palestra MM - Saúde Bucal' AND start_datetime::date = '2025-10-25';
UPDATE public.events SET unit = 'Nilópolis' WHERE title = 'Ação voluntários UNIMETROCAMP' AND start_datetime::date = '2025-10-24';
UPDATE public.events SET unit = 'DIC' WHERE title = 'Palestra Finanças' AND start_datetime::date = '2025-10-28';
UPDATE public.events SET unit = 'DIC' WHERE title = 'Palestra Sobre Autocuidado' AND start_datetime::date = '2025-10-30';
UPDATE public.events SET unit = 'DIC' WHERE title = 'Papel da educação na transformação pessoal e social' AND start_datetime::date = '2025-10-29';
UPDATE public.events SET unit = 'Nilópolis' WHERE title = 'Encontro de Famílias' AND start_datetime::date = '2025-11-08';
UPDATE public.events SET unit = 'Santana' WHERE title = 'ESPRO' AND start_datetime::date = '2025-11-12';
UPDATE public.events SET unit = 'Santana' WHERE title = 'Sorriso é Coisa Séria' AND start_datetime::date = '2025-11-06';
UPDATE public.events SET unit = 'DIC' WHERE title = 'Festa da Primaveira' AND start_datetime::date = '2025-11-22';
UPDATE public.events SET unit = 'Santana' WHERE title = 'TROCA DE FAIXA KARATÊ' AND start_datetime::date = '2025-12-05';
UPDATE public.events SET unit = 'Santana' WHERE title = 'Recital' AND start_datetime::date = '2025-11-30';
UPDATE public.events SET unit = 'DIC' WHERE title = 'Palestra Saúde Emocional' AND start_datetime::date = '2025-11-28';
UPDATE public.events SET unit = 'DIC' WHERE title = 'Parada de Natal' AND start_datetime::date = '2025-12-06';
UPDATE public.events SET unit = 'DIC' WHERE title = 'Coral Ana Dic - Igreja do Nazareno Jardim Aeronave' AND start_datetime::date = '2025-12-07';
UPDATE public.events SET unit = 'DIC' WHERE title = 'Natal Feliz - Manaim' AND start_datetime::date = '2025-12-13';
UPDATE public.events SET unit = 'DIC' WHERE title = 'Espetaculo Principe do Egito' AND start_datetime::date = '2025-12-19';
UPDATE public.events SET unit = 'DIC' WHERE title = 'Cantata de Natal  ( Natal Brasileiro)' AND start_datetime::date = '2025-12-21';
UPDATE public.events SET unit = 'DIC' WHERE title = 'CAFÉ DA MANHÃ COM FAMILIAS' AND start_datetime::date = '2026-02-21';
UPDATE public.events SET unit = 'Nilópolis' WHERE title = 'VARAL SOLIDÁRIO' AND start_datetime::date = '2026-02-28';
UPDATE public.events SET unit = 'Nilópolis' WHERE title = 'ENCONTRO DE FAMILIA' AND start_datetime::date = '2026-03-07';
UPDATE public.events SET unit = 'Santana' WHERE title = 'Encontro de Famílias' AND start_datetime::date = '2026-03-21';
UPDATE public.events SET unit = 'DIC' WHERE title = 'VARAL SOLIDÁRIO' AND start_datetime::date = '2026-03-21';
UPDATE public.events SET unit = 'Santana' WHERE title = 'Teatro de Páscoa' AND start_datetime::date = '2026-03-30';
UPDATE public.events SET unit = 'Nilópolis' WHERE title = 'Café da manhã especial' AND start_datetime::date = '2026-03-26';
UPDATE public.events SET unit = 'Nilópolis' WHERE title = 'Teatro de Páscoa' AND start_datetime::date = '2026-03-30';
UPDATE public.events SET unit = 'Nilópolis' WHERE title = 'HOPE DAY' AND start_datetime::date = '2026-03-28';
UPDATE public.events SET unit = 'DIC' WHERE title = 'Ação Otica Prime' AND start_datetime::date = '2026-03-30';
UPDATE public.events SET unit = 'DIC' WHERE title = 'Roda de Conversa (Saúde Emocional)' AND start_datetime::date = '2023-03-31';
UPDATE public.events SET unit = 'DIC' WHERE title = 'Visita Empresa Brasiliense' AND start_datetime::date = '2026-03-30';
UPDATE public.events SET unit = 'DIC' WHERE title = 'Ação Social - Objetivo' AND start_datetime::date = '2026-04-02';
UPDATE public.events SET unit = 'Nilópolis' WHERE title = 'Páscoa - JNI' AND start_datetime::date = '2026-04-04';
UPDATE public.events SET unit = 'DIC' WHERE title = 'Exposição Carbono Zero' AND start_datetime::date = '2026-03-31';
UPDATE public.events SET unit = 'DIC' WHERE title = 'Culto de Páscoa e almoço especial' AND start_datetime::date = '2026-04-02';
UPDATE public.events SET unit = 'DIC' WHERE title = 'Palestra Com Grupo MM - Primeiros Socorros' AND start_datetime::date = '2026-04-25';
UPDATE public.events SET unit = 'Santana' WHERE title = 'Integração funcionários- Social' AND start_datetime::date = '2026-04-17';
UPDATE public.events SET unit = 'DIC' WHERE title = 'Encontro de Profissões' AND start_datetime::date = '2026-05-09';
UPDATE public.events SET unit = 'DIC' WHERE title = 'Encontro de mulheres - Mulheres que florescem' AND start_datetime::date = '2026-05-30';
UPDATE public.events SET unit = 'DIC' WHERE title = 'Baile da Pessoa Idosa' AND start_datetime::date = '2026-04-30';
UPDATE public.events SET unit = 'DIC' WHERE title = 'Entrega dos óculos com Parceiro Otica Prime' AND start_datetime::date = '2026-04-29';
UPDATE public.events SET unit = 'DIC' WHERE title = 'Abertura do Congemas' AND start_datetime::date = '2026-05-07';
UPDATE public.events SET unit = 'DIC' WHERE title = 'Passeata 18 de Maio' AND start_datetime::date = '2026-05-15';
UPDATE public.events SET unit = 'DIC' WHERE title = 'Festa da Amizade' AND start_datetime::date = '2026-05-28';
UPDATE public.events SET unit = 'DIC' WHERE title = 'Bazar Ana Dic' AND start_datetime::date = '2026-05-25';
UPDATE public.events SET unit = 'Nilópolis' WHERE title = 'Ação 18  Maio' AND start_datetime::date = '2026-05-23';