INSERT INTO public.events (title, description, start_datetime, end_datetime, unit, event_type, visibility, status, created_by, notes) VALUES ('Encontro de Famílias', 'Receberemos as famílias com um café da manhã, na sequencia teremos apresentações da crianças e uma palavra final.', '2025-11-08 09:00:00+00', '2025-11-08 11:00:00+00', 'Nilópolis', 'interno', 'interno', 'confirmado', 'mkt@anabrasil.org', 'Alimentação: Itens de café da manhã, como: bolo simples, frutas e pão.
Materiais: 
Equipamento: Não'),('ESPRO', 'Projeto do Gestores do Futuro planejou um dia de brincadeiras para as crianças. Laços da Esperança tem como missão promover acolhimento, educação e alegria para crianças vulneráveis, oferecendo oportunidades de desenvolvimento integral e construindo vínculos transformadores com dignidade e afeto', '2025-11-12 08:00:00+00', '2025-11-12 10:00:00+00', 'Santana', 'interno', 'interno', 'confirmado', 'mkt@anabrasil.org', 'Alimentação: NÃO
Materiais: 
Equipamento: NÃO'),('Sorriso é Coisa Séria', 'Na atividade proposta, crianças da instituição ANA - Santana, de 06 a 10 anos, participarão de atividades lúdico educativas de saúde bucal realizadas pela equipe de dentistas do Sesc Campinas, com orientações sobre cuidados e higiene e distribuição de kits de saúde bucal. A ação será complementada pela intervenção "O Mundo em Minha Boca", na qual o grupo propõe um resgate poético e musical sobre as funções da boca como meio de experimentação do mundo e forma de expressão. O espetáculo é interativo e integrado com uma oficina de origami.', '2025-11-06 08:30:00+00', '2025-11-06 10:30:00+00', 'Santana', 'interno', 'interno', 'confirmado', 'mkt@anabrasil.org', 'Alimentação: NÃO
Materiais: 
Equipamento: NÃO'),('Festa da Primaveira', 'O Evento tem o intuito de promover a integração e fortalecer os vinculos entro os participantes e a comunidade local', '2025-11-22 14:00:00+00', '2025-11-22 16:00:00+00', 'DIC', 'externo', 'interno', 'confirmado', 'mkt@anabrasil.org', 'Alimentação: sim
Materiais: 
Equipamento: não'),('TROCA DE FAIXA KARATÊ', 'Atividade de Karatê vai trocar a faixa  ', '2025-12-05 14:00:00+00', '2025-12-05 16:00:00+00', 'Santana', 'interno', 'interno', 'confirmado', 'mkt@anabrasil.org', 'Alimentação: não
Materiais: 
Equipamento: não'),('Recital', 'Apresentação da Flauta com parceria com igreja Presbiteriana', '2025-11-30 09:00:00+00', '2025-11-30 11:00:00+00', 'Santana', 'externo', 'publico', 'confirmado', 'mkt@anabrasil.org', 'Alimentação: Não
Materiais: 
Equipamento: não'),('Palestra Saúde Emocional', 'Palestra Saúde Emocional, com pastor e psicologo Fred Dias', '2025-11-28 09:00:00+00', '2025-11-28 11:00:00+00', 'DIC', 'interno', 'interno', 'confirmado', 'mkt@anabrasil.org', 'Alimentação: Não
Materiais: 
Equipamento: Não'),('Parada de Natal', 'A Parada de Natal deste ano acontecerá na Avenida Francisco Glicério e  será um momento especial de celebração, integração e alegria para toda a comunidade. O evento contará com apresentações temáticas, música, personagens natalinos, carros decorados e diversas intervenções artísticas que vão transformar a avenida em um verdadeiro cenário mágico de fim de ano.', '2025-12-06 19:00:00+00', '2025-12-06 21:00:00+00', 'DIC', 'externo', 'interno', 'confirmado', 'mkt@anabrasil.org', 'Alimentação: Não
Materiais: 
Equipamento: não'),('Coral Ana Dic - Igreja do Nazareno Jardim Aeronave', 'Nosso coral fará uma apresentação especial de Natal ', '2025-12-07 18:00:00+00', '2025-12-07 20:00:00+00', 'DIC', 'externo', 'interno', 'confirmado', 'mkt@anabrasil.org', 'Alimentação: não
Materiais: 
Equipamento: não'),('Natal Feliz - Manaim', 'O Natal Feliz do Manaim será  um dia de celebração, solidariedade e integração entre as três unidades do Social, que se uniram para proporcionar uma experiência inesquecível aos nossos usuários. Este ano, contamos com o apoio fundamental do Hopy Day,  Alcance e da JNI.', '2025-12-13 07:00:00+00', '2025-12-13 09:00:00+00', 'DIC', 'externo', 'interno', 'confirmado', 'mkt@anabrasil.org', 'Alimentação: Sim, estamos precisando de doação de carne, pernil ou frango
Materiais: 
Equipamento: não'),('Espetaculo Principe do Egito', 'O Serviço de Convivência e Fortalecimento de Vínculos está preparando uma apresentação especial baseada na história do “Príncipe do Egito”, desenvolvida integralmente pelos nossos usuários, com acompanhamento da equipe técnica e educadores. O espetáculo busca promover protagonismo, criatividade e fortalecimento de vínculos comunitários por meio da arte, música e expressão corporal.', '2025-12-19 19:00:00+00', '2025-12-19 21:00:00+00', 'DIC', 'externo', 'interno', 'confirmado', 'mkt@anabrasil.org', 'Alimentação: sim, caixinhas de suco, pão, bolinhos
Materiais: 
Equipamento: não'),('Cantata de Natal  ( Natal Brasileiro)', 'Cantata de Natal Igreja Jardim Aeronave com Participação CCII', '2025-12-21 09:00:00+00', '2025-12-21 11:00:00+00', 'DIC', 'externo', 'interno', 'confirmado', 'mkt@anabrasil.org', 'Alimentação: Não
Materiais: 
Equipamento: Não'),('CAFÉ DA MANHÃ COM FAMILIAS', 'NO DIA 21/02/2026 TEREMOS NOSSO CAFÉ COM FAMILIAS, ONDE TEREMOS A PRESENÇA DA SECRETARIA DA ASSISTENCIA SOCIAL - VANDERCLÉIA MORO. SERÁ UM ENCONTRO INFORMATIVO, ONDE AS FAMILIAS RECEBERÃO INFORMAÇÕES SOBRE NOSSO SERVIÇO, E TAMBÉM SOBRE SERVIÇOS, QUE HOJE ESTÃO DISPONIVEIS PARA A COMUNIDADE. SERÁ DIVULGADO NESTE DIA, O PRIMEIRO VARAL SOLIDARIO DO ANA DIC, EM PARCERIA COM A SECRETARIA DA ASSISTENCIA. ', '2026-02-21 09:00:00+00', '2026-02-21 11:00:00+00', 'DIC', 'externo', 'publico', 'confirmado', 'mkt@anabrasil.org', 'Alimentação: PRECISAMOS DE DOAÇÕES DE PRESUNTO / MUSSARELA / SUCO / BRINDES DIVERSOS . 
Materiais: 
Equipamento: NÃO '),('VARAL SOLIDÁRIO', 'O Varal Solidário, na Unidade Nilópolis, em parceria com o Programa Próximo Passo. Será uma manhã especial de cuidado, orientação e apoio às famílias da comunidade.', '2026-02-28 09:00:00+00', '2026-02-28 11:00:00+00', 'Nilópolis', 'interno', 'publico', 'confirmado', 'mkt@anabrasil.org', 'Alimentação: não
Materiais: 
Equipamento: não'),('ENCONTRO DE FAMILIA', 'Um momento para apresentar nossas atividades , explicar nosso serviço de apoio com  Serviço Social e Psicologia, e  se encantar com o talento das crianças nas apresentações.', '2026-03-07 09:00:00+00', '2026-03-07 11:00:00+00', 'Nilópolis', 'interno', 'interno', 'confirmado', 'mkt@anabrasil.org', 'Alimentação: não
Materiais: 
Equipamento: não') ON CONFLICT DO NOTHING;